### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by RiadOkba** [vanduong185/translation-notes#11]
1- the require('./index') is not accepted: require not recognized! -> you have to include requirejs

2- google translate not visible. you need to review your index.js code

**Comment by vanduong185** [comment]
> 1- the require('./index') is not accepted: require not recognized! -> you have to include requirejs
> 
> 2- google translate not visible. you need to review your index.js code

Thank you, I'll check it soon.

**Comment by vanduong185** [comment]
@RiadOkba I fixed it. So happy if you check it again. I closed this issue. Thank you so much 🥂
